stages:
  process_data:
    cmd: python3 process_data.py
    deps:
    - data/IMDB_movie_ratings_sentiment.csv
    - process_data.py
    params:
    - data_path
    - output_path
    - process
    outs:
    - data/processed/X_test.txt
    - data/processed/X_train.txt
    - data/processed/y_test.txt
    - data/processed/y_train.txt
  train:
    cmd: python3 train_sklearn.py
    deps:
    - data/processed/X_test.txt
    - data/processed/X_train.txt
    - data/processed/y_test.txt
    - data/processed/y_train.txt
    - train_sklearn.py
    params:
    - model_path
    - output_path
    - train
    - output_path
    outs:
    - models/model.joblib
  predict:
    foreach:
      - train
      - test
    do:
      cmd: >-
        python3 predict.py
        --data_path data/processed/X_${item}.txt
        --pred_path data/predictions/y_${item}_pred.txt
      deps:
      - data/processed/X_${item}.txt
      - models/model.joblib
      - predict.py
      outs:
      - data/predictions/y_${item}_pred.txt
  evaluate:
    foreach:
      - train
      - test
    do:
      cmd: >-
        python3 evaluate.py
        --pred_path data/predictions/y_${item}_pred.txt
        --true_path data/processed/y_${item}.txt
        --metrics_path results/${item}_metrics.json
      deps:
      - data/predictions/y_${item}_pred.txt
      - data/processed/y_${item}.txt
      - evaluate.py
      metrics:
      - results/${item}_metrics.json
