stages:
  process_data:
    cmd: python3 process_data.py
    deps:
    - data/IMDB_movie_ratings_sentiment.csv
    - process_data.py
    params:
    - data_path
    - output_path
    - process
    outs:
    - data/processed/X_test.txt
    - data/processed/X_train.txt
    - data/processed/y_test.txt
    - data/processed/y_train.txt
  train:
    cmd: python3 train_sklearn.py
    deps:
    - data/processed/X_test.txt
    - data/processed/X_train.txt
    - data/processed/y_test.txt
    - data/processed/y_train.txt
    - train_sklearn.py
    params:
    - model_path
    - output_path
    - train
    outs:
    - models/model.joblib
    metrics:
    - results/metrics.json
