stages:
  process_data:
    cmd: python3 process_data.py
    deps:
    - data/IMDB_movie_ratings_sentiment.csv
    - process_data.py
    params:
    - process
    outs:
    - data/processed/X_test.txt
    - data/processed/X_train.txt
    - data/processed/y_test.txt
    - data/processed/y_train.txt
  train:
    cmd: >-
      python3 train_sklearn.py
      --split-data-path ./data/processed
      --model-path ./models/model.joblib
      --metrics-path ./results/metrics.json
      --min-df ${train.min_df}
      --max-df ${train.max_df}
      --max-ngrams ${train.max_ngrams}
      --stopwords ${train.stopwords}
      --loss ${train.loss}
      --learning-rate ${train.learning_rate}
    deps:
    - data/processed/X_test.txt
    - data/processed/X_train.txt
    - data/processed/y_test.txt
    - data/processed/y_train.txt
    - train_sklearn.py
    params:
    - train
    outs:
    - models/model.joblib
    metrics:
    - results/metrics.json
